#pragma checksum "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "c7e7fb49238a3a2d05d68cf6963a5dd8c0258f0fadd45ad2dcc2d753acb5fd47"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Security_complainview), @"mvc.1.0.view", @"/Views/Security/complainview.cshtml")]
namespace AspNetCore
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\_ViewImports.cshtml"
using WebApplication3

#nullable disable
    ;
#nullable restore
#line 2 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\_ViewImports.cshtml"
using WebApplication3.Models

#line default
#line hidden
#nullable disable
    ;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"c7e7fb49238a3a2d05d68cf6963a5dd8c0258f0fadd45ad2dcc2d753acb5fd47", @"/Views/Security/complainview.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"35f6ccac35bf5b6580930131dd8a00f4fbff89fbaff8a6ea9c72496c82fab2a6", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Security_complainview : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<WebApplication3.Models.Complain>>
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
  
    ViewData["Title"] = "complainview";
    Layout = "~/Views/Shared/security.cshtml";

#line default
#line hidden
#nullable disable

            WriteLiteral("<div class=\"container py-5\">\r\n\r\n    <div class=\"card\">\r\n        <div class=\"card-body\">\r\n            <div class=\"mb-4 pb-2 align-items-center\">\r\n                <h5 class=\"mb-0\">Complain List</h5>\r\n");
            WriteLiteral("            </div>\r\n            <div class=\"table-responsive pb-4\">\r\n                <table  class=\"table table-striped table-bordered border text-nowrap align-middle\">\r\n\r\n    <thead>\r\n        <tr>\r\n            <th>\r\n                ");
            Write(
#nullable restore
#line 21 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayNameFor(model => model.Details)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            Write(
#nullable restore
#line 24 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayNameFor(model => model.Personname)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            Write(
#nullable restore
#line 27 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayNameFor(model => model.Status)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            Write(
#nullable restore
#line 30 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayNameFor(model => model.Cdate)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            Write(
#nullable restore
#line 33 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayNameFor(model => model.Rdate)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            Write(
#nullable restore
#line 36 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayNameFor(model => model.Type)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </th>         \r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");
#nullable restore
#line 41 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
 foreach (var item in Model) {

#line default
#line hidden
#nullable disable

            WriteLiteral("        <tr>\r\n            <td>\r\n                ");
            Write(
#nullable restore
#line 44 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayFor(modelItem => item.Details)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            Write(
#nullable restore
#line 47 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayFor(modelItem => item.Personname)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            Write(
#nullable restore
#line 50 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayFor(modelItem => item.Status)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            Write(
#nullable restore
#line 53 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayFor(modelItem => item.Cdate)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            Write(
#nullable restore
#line 56 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayFor(modelItem => item.Rdate)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            Write(
#nullable restore
#line 59 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
                 Html.DisplayFor(modelItem => item.Type)

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("\r\n            </td>\r\n");
            WriteLiteral("\r\n        </tr>\r\n");
#nullable restore
#line 74 "D:\WebApplication3(w)\WebApplication3\WebApplication3\WebApplication3\Views\Security\complainview.cshtml"
}

#line default
#line hidden
#nullable disable

            WriteLiteral(@"    </tbody>
</table>
                
            </div>
        </div>
        <style>
            /* Enhance table design */
            table {
                border-collapse: collapse;
                width: 100%;
            }

            .table thead th {
                text-transform: uppercase;
                text-align: center;
            }

            .table td,
            .table th {
                text-align: center;
                vertical-align: middle;
            }

            .btn {
                text-transform: uppercase;
                font-size: 0.875rem;
            }

            .container h1 {
                color: #333;
            }
        </style>
");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<WebApplication3.Models.Complain>> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
